выполнила три задачи из домашнего задания
js-tasks-ru/js-20220513_alefed89 pull request #2
Opened 2022-05-19 22:04 UTC by Dariia89

2022-05-19 22:05 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-05-20 12:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const sorted = JSON.parse(JSON.stringify(arr));
`JSON.parse(JSON.stringify(arr))` так делать крайне нежелательно.
Для копирования массива воспользуйтесь следующим подходом:
```
const copy = [...arr]
```

2022-05-20 12:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sorted.sort((a, b) => a.localeCompare(b, ['ru', 'en'], { caseFirst: 'upper'}));
в данном решении есть дубликаты кода, подумайте как от этого избавиться

2022-05-20 12:29 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>  export const pick = (obj, ...fields) => {
👍 good

2022-05-20 12:29 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
👍 good

2022-05-20 12:29 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2022-05-20 14:04 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-05-20 18:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-05-24 07:19 UTC, dosandk approved these changes
👍 good

2022-05-24 07:19 UTC, merged